Repository benxene/7days-50projects, pull requests merged in 2020-12, with the labels that each got.

#2 Landing page [beta]
  public/index.png
  src/components/Project.tsx
  src/components/Utilities.tsx
  src/constants/theme.ts
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: enhancement, feature

#6 added react-icons
  package-lock.json
  package.json
  src/components/Project.tsx
Labels: enhancement

#10 To Do list project added
  src/pages/todolist.tsx
Labels: feature

#11 Rotating navigation animation Day3 completed
  public/batman.jpg
  src/pages/rotating-navigation-animation.tsx
Labels: feature

#14 Added Password Generator
  src/components/Utilities.tsx
  src/functions/password-generator.ts
  src/helpers/passgen-reducer.ts
  src/pages/mobile-nav.tsx
  src/pages/password-generator.tsx
Labels: feature

#25 added ripple button (#18)
  src/components/RippleButton.tsx
  src/pages/ripple-button.tsx
Labels: enhancement, feature

#30 added key press details
  src/pages/_app.tsx
  src/pages/key-press-details.tsx
Labels: feature

#20 Blurry Loading added Day 5
  package-lock.json
  public/blurry-load-img.jpg
  src/pages/blurry-loading.tsx
Labels: feature

#28 added notes-app
  src/components/Note.tsx
  src/pages/notes-app.tsx
Labels: feature

#36 added added random image feed
  next.config.js
  src/components/Utilities.tsx
  src/pages/random-image-feed.tsx
Labels: feature

#38 added password strength background blur
  src/components/RippleButton.tsx
  src/pages/password-strength-blur.tsx
  src/pages/ripple-button.tsx
Labels: enhancement, feature

#44 added animated testimonial box
  src/constants/testimonials.ts
  src/pages/testimonial.tsx
Labels: feature

#41 Split landing page completed
  public/ps5.png
  public/xbox.jpg
  src/pages/split-landing-page.tsx
Labels: feature

#46 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement, good first issue, help wanted

#52 Quiz App completed
  src/constants/quiz-questions.ts
  src/pages/quiz-app.tsx
Labels: feature

#59 Auto text effect added (Day 30)
  src/pages/auto-text-effect.tsx
Labels: feature

#51 Added Netflix Mobile Navigation
  next.config.js
  src/components/Utilities.tsx
  src/pages/netflix-nav.tsx
Labels: feature

#63 Added Good cheap fast
  src/components/Switch.tsx
  src/pages/good-cheap-fast.tsx
Labels: feature

#65 Add Kinetic Loader (Day 23)
  src/pages/kinetic-loader.tsx
Labels: feature

#66 expanding card added (Day 1)
  src/pages/expanding-cards.tsx
Labels: feature

#72 added custom slider
  src/components/Slider.tsx
  src/pages/custom-slider.tsx
Labels: feature

#73 Add Drink Water (Day 16)
  src/pages/drink-water.tsx
Labels: feature

#71 sound board added (Day 9)
  public/sounds/applause.mp3
  public/sounds/boo.mp3
  public/sounds/gasp.mp3
  public/sounds/tada.mp3
  public/sounds/victory.mp3
  public/sounds/wrong.mp3
  src/pages/sound-board.tsx
Labels: feature

#68 Added Instagram themed double-tap-like
  src/components/Avatar.tsx
  src/components/InstaPost.tsx
  src/pages/double-click-like.tsx
Labels: feature

#75 hoverboard added (Day 36)
  src/pages/hoverboard.tsx
Labels: feature

#69 wave form added (Day 8)
  src/pages/wave-form.tsx
Labels: feature

#79 Add Animated Nav (Day 14)
  src/pages/animated-nav.tsx
Labels: feature

#80 Added sticky nav
  src/components/NavigationBar.tsx
  src/pages/index.tsx
Labels: feature

#84 faq added(Day 12)
  src/components/ExpansionPanel.tsx
  src/pages/faq.tsx
Labels: feature

#85 Add Image Carousel (Day 35)
  src/pages/image-carousel.tsx
Labels: feature

#83 added theme clock
  src/components/Utilities.tsx
  src/pages/netflix-nav.tsx
  src/pages/theme-clock.tsx
Labels: feature

#91 Add Feedback UI Design Completed (Day 43)
  src/components/Rating.tsx
  src/pages/feedback-ui.tsx
Labels: feature

#90 Added OTP Input Box
  src/pages/otp-ui.tsx
Labels: feature

#93 added skeleton loader
  src/constants/theme.ts
  src/pages/skeleton.tsx
Labels: feature

#97 Added movies app
  next.config.js
  src/components/MovieCard.tsx
  src/pages/movies-app.tsx
Labels: feature

#89 live user filter added
  src/pages/live-user-filter.tsx
Labels: feature

#100 Animated countdown added
  src/pages/animated-countdown.tsx
Labels: feature

#101 Added Vertical Slider (Day 26)
  src/constants/theme.ts
  src/pages/vertical-slider.tsx
Labels: feature

#112 Add Background slider (Day 18)
  src/pages/background-slider.tsx
Labels: feature

#113 Scroll Animation build error fix
  src/pages/scroll-animation.tsx
Labels: feature

#114 added 3d background box
  src/pages/3d-background-boxes.tsx
Labels: feature

#92 Added Toast Notification (Day 27)
  src/pages/toast-notification.tsx
Labels: feature

#108 bug fixes (#107, #106)
  src/pages/blurry-loading.tsx
  src/pages/hidden-search-widget.tsx
Labels: bug, enhancement

#111 drawing app added (Day 22)
  src/pages/drawing-app.tsx
Labels: feature

#104 Drag drop
  .prettierrc
  src/pages/drag-drop.tsx
Labels: feature

#117 added dev.to social card
  src/pages/social-card.tsx
Labels: feature

#116 added pokedex[Day 37]
  src/pages/pokedex.tsx
Labels: feature

#118 fix warning: moved styled component 'Dex' out of 'Pokemon'
  src/pages/pokedex.tsx
Labels: bug, enhancement

#115 updates to index page
  next.config.js
  public/index.png
  public/screenshots/3d-background-boxes.jpg
  public/screenshots/animated-countdown.jpg
  public/screenshots/animated-nav.jpg
  public/screenshots/auto-text-effect.jpg
  public/screenshots/background-slider.jpg
  public/screenshots/blurry-loading.jpg
  public/screenshots/custom-slider.jpg
  public/screenshots/dad-jokes.jpg
  public/screenshots/double-click-like.jpg
  public/screenshots/drag-drop.jpg
  public/screenshots/drink-water.jpg
  public/screenshots/drwaing-app.jpg
  public/screenshots/expanding-cards.jpg
  public/screenshots/faq.jpg
  public/screenshots/feedback-ui.jpg
  public/screenshots/github-profile.jpg
  public/screenshots/good-cheap-fast.jpg
  public/screenshots/hidden-search-widget.jpg
  public/screenshots/hoverboard.jpg
  public/screenshots/image-carousel.jpg
  public/screenshots/incrementing-counter.jpg
  public/screenshots/index.jpg
  public/screenshots/key-press-details.jpg
  public/screenshots/kinetic-loader.jpg
  public/screenshots/live-user-filter.jpg
  public/screenshots/mobile-nav.jpg
  public/screenshots/movies-app.jpg
  public/screenshots/netflix-nav.jpg
  public/screenshots/notes-app.jpg
  public/screenshots/otp-ui.jpg
  public/screenshots/password-generator.jpg
  public/screenshots/password-strength-blur.jpg
  public/screenshots/pokedex.jpg
  public/screenshots/progress-steps.jpg
  public/screenshots/quiz-app.jpg
  public/screenshots/random-choice-picker.jpg
  public/screenshots/random-image-feed.jpg
  public/screenshots/ripple-button.jpg
  public/screenshots/rotating-navigation-animation.jpg
  public/screenshots/scroll-animation.jpg
  public/screenshots/skeleton.jpg
  public/screenshots/social-card.jpg
  public/screenshots/sound-board.jpg
  public/screenshots/split-landing-page.jpg
  public/screenshots/testimonial.jpg
  public/screenshots/theme-clock.jpg
  public/screenshots/toast-notification.jpg
  public/screenshots/todolist.jpg
  public/screenshots/vertical-slider.jpg
  public/screenshots/wave-form.jpg
  src/components/DevCard.tsx
  src/components/Footer.tsx
  src/components/NavigationBar.tsx
  src/components/Project.tsx
  src/components/Utilities.tsx
  src/pages/index.tsx
Labels: enhancement, feature

#122 Bug fixes and pre-deploy fixes
  public/screenshots/drawing-app.jpg
  src/pages/api/get-projects.ts
  src/pages/index.tsx
Labels: bug, enhancement

#123 bug fixes: for production
  .gitignore
  next.config.js
  package.json
  src/components/Footer.tsx
  src/components/NavigationBar.tsx
  src/pages/api/get-projects.ts
  src/pages/index.tsx
Labels: bug, enhancement

#125 README updated
  README.md
Labels: documentation

#126 Index page update
  public/next-js.svg
  public/styledcomponent.png
  public/typescript.png
  src/components/NavigationBar.tsx
  src/components/Project.tsx
  src/pages/index.tsx
Labels: enhancement

#127 readme-update
  README.md
Labels: enhancement

#128 responsiveness bug fixes
  src/components/MovieCard.tsx
  src/pages/index.tsx
Labels: bug, enhancement
